
let button = document.querySelector('.button');

button.addEventListener('click', (e) => {
  alert("You're such a rebel!");
  
})

/*
This file has been edited in Jan 2023.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.

*/
