
let button = document.querySelector('.button');

button.addEventListener('click', (e) => {
  alert("You're such a rebel!");
  
})

/*
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment. 
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.
This file is too long, because of this code comment.

*/